### ISSUE TITLE
ClientRequest complaining about missing User-Agent header. 

### ISSUE THREAD

**Issue by nihakue** [johnwyles/node-nest-api#5]
Running through the example in the README, and received the following Error:
```
> Error: "value" required in setHeader("User-Agent", value)
    at ClientRequest.setHeader (_http_outgoing.js:357:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.request (http.js:26:10)
    at Object.request (https.js:199:15)
    at NestApi.get (/Users/gabriel/nesting/node_modules/nest-api/lib/nest-api.js:145:21)
    at /Users/gabriel/nesting/node_modules/nest-api/lib/nest-api.js:169:19
    at /Users/gabriel/nesting/node_modules/nest-api/lib/nest-api.js:59:16
    at IncomingMessage.<anonymous> (/Users/gabriel/nesting/node_modules/nest-api/lib/nest-api.js:120:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

Adding a fake User-Agent to the options in NestApi.prototype.get makes the Error go away, but I'm not sure how you'd like to solve the problem.

```
$node --version
v7.3.0
```

yarn.lock:
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


coffee-script@:
  version "1.12.2"
  resolved "https://registry.yarnpkg.com/coffee-script/-/coffee-script-1.12.2.tgz#0d4cbdee183f650da95419570c4929d08ef91376"

nest-api@^0.0.7:
  version "0.0.7"
  resolved "https://registry.yarnpkg.com/nest-api/-/nest-api-0.0.7.tgz#4e1f414c6433fb6b409dc89611f94c885954a154"
  dependencies:
    coffee-script ""
```

**Comment by nihakue** [comment]
Looks like @userAgent is undefined? I suspect my node version is to blame.

**Comment by KenDodman** [comment]
just solved it by editing nest_api.js line 138, and changing 'User-Agent': this.useragent
to 
'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1309.0 Safari/537.17"
